# -*- coding: utf-8 -*-
"""SVM_kelulusan.ipynb

Automatically generated by Colaboratory.
"""

# =============================================================================
# PROJECT MACHINE LEARNING - SVM
# Prediksi Kelulusan Mahasiswa
# =============================================================================

"""
Nama: [NAMA ANDA]
NIM: [NIM ANDA]
Kelas: [KELAS ANDA]
"""

# ============================================
# CELL 1: UPLOAD DATASET
# ============================================
from google.colab import files
import pandas as pd
import io
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

print("📤 UPLOAD FILE 'datakelulusanmahasiswa.csv'")
print("Klik 'Choose Files' dan pilih file dataset Anda")
print("=" * 50)

# Upload file
uploaded = files.upload()

# Baca dataset
file_name = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[file_name]))

print(f"✅ Dataset berhasil diupload: {file_name}")
print(f"📊 Jumlah data: {df.shape[0]} baris, {df.shape[1]} kolom")
print("\n5 data pertama:")
print(df.head())
print("\nInformasi dataset:")
print(df.info())